apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-account 
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: order-service
#   labels:
#     app: order-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: order-service
#   template:
#     metadata:
#       labels:
#         app: order-service
#       annotations:
#         dapr.io/enabled: "true"  # Enable Dapr sidecar injection
#         dapr.io/app-id: "order-service"
#         dapr.io/app-port: "5000"
        dapr.io/enable-mtls: "true"  # mTLS activé automatiquement par Dapr
    spec:
      serviceAccountName: order-service-account  # Use the service account created above
#       containers:
#         - name: order-service
#           image: order-service  # Use the image built in the previous step
#           ports:
#             - containerPort: 5000  # Port on which the application listens
#           env:  
#             - name: QUARKUS_DATASOURCE_URL 
#               value: jdbc:mysql://postgres-service:5432/order_db
#             - name: POSTGRES_USER
#               value: postgres
#             - name: POSTGRES_PASSWORD
#               value: postgres
#           resources:
#             requests:
#               memory: "256Mi"
#               cpu: "500m"
#             limits:
#               memory: "512Mi"
#               cpu: "1"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: order-service
# spec:
#   selector:
#     app: order-service
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
