apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-binding
spec:
  type: bindings.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=postgres-service user=postgres password=postgres port=5432 database=customer_db"
