version: '3.8'
services:
  order-service:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

