apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-account 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        dapr.io/enabled: "true"  # Enable Dapr sidecar injection
        dapr.io/app-id: "product-service"
        dapr.io/app-port: "8090"
        dapr.io/enable-mtls: "true"  # mTLS activé automatiquement par Dapr
        dapr.io/config: "dapr-config"
    spec:
      serviceAccountName: product-service-account  # Use the service account created above
      containers:
        - name: product-service
          image: amine20akka/product-service:v8
          ports:
            - containerPort: 8090
          env:
            - name: QUARKUS_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/product_db
            - name: QUARKUS_DATASOURCE_USERNAME
              value: root
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: root
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30003
